# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventoryItem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import book_pb2 as book__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13inventoryItem.proto\x1a\nbook.proto\"\x99\x01\n\rInventoryItem\x12\x13\n\x0binventoryId\x18\x01 \x02(\t\x12\x15\n\x04item\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12\x30\n\x06status\x18\x03 \x01(\x0e\x32\x15.InventoryItem.Status:\tAVAILABLE\"\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x01\x12\t\n\x05TAKEN\x10\x02\x42\x06\n\x04type')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventoryItem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INVENTORYITEM._serialized_start=36
  _INVENTORYITEM._serialized_end=189
  _INVENTORYITEM_STATUS._serialized_start=147
  _INVENTORYITEM_STATUS._serialized_end=181
# @@protoc_insertion_point(module_scope)
